[build]
builder = "nixpacks"
buildCommand = "npm run install-deps && npm run build"

[deploy]
startCommand = "NODE_ENV=production npm start --omit=dev"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"